version: '3.5'

services:
    database:
        container_name: database
        image: mysql:5.7.22
        environment:
            TZ: America/Recife
            MYSQL_DATABASE: 'crud_usuario'
            MYSQL_ROOT_PASSWORD: 'Root1234'
        networks:
            - network
        ports:
            - "3306:3306"

    application:
        container_name: application
        environment:
            TZ: America/Recife
        build:
            context: ../
            dockerfile: Docker/Dockerfile
        networks:
            - network
        ports:
            - "8080:8080"
        depends_on:
            - database

networks:
  network:
    name: network
    driver: bridge
