name: Deploy to Production

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    environment: production
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Rebuild
        run: doctl app create-deployment --force-rebuild ${{ secrets.DIGITALOCEAN_APPLICATION_ID }}
