name: Test Application

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    name: test
    environment: testing
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      
      - name: Test application
        run: >
          npm install && npm run test
