name: Test Application

on:
  push:

jobs:
  test:
    name: testing
    environment: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      
      - name: Test application
        run: >
          cd ./app && npm install && npm run test
